[tool.poetry]
name = "microemg-software"
version = "0.1.0"
description = ""
authors = ["Gabrielle M. Schroeder <8205451+gmschroe@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
numpy = "^1.26.3"
matplotlib = "^3.8.2"
scipy = "^1.11.4"
pymicroemg = {path = "analysis_software/pymicroemg", develop = true}
intanutil = {path = "analysis_software/intanutil", develop = true}
pyside6 = "^6.6.1"
microemggui = {path = "analysis_software/microemggui", develop = true}
pyqtgraph = "^0.13.4"
palettable = "^3.3.3"
scikit-learn = "^1.5.0"
scikit-image = "^0.24.0"

[tool.poetry.group.dev.dependencies]
black = "^24.4.0"
pre-commit = "^3.6.0"
mypy = "^1.8.0"
flake8 = "^7.0.0"
flake8-bugbear = "^24.1.17"
pytest = "^8.0.2"
pytest-qt = "^4.4.0"
pytest-check = "^2.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
exclude = ["analysis_software/intanutil/"]
ignore_missing_imports = true
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
strict_equality = true
check_untyped_defs = true
disallow_subclassing_any = true
disallow_untyped_decorators = true

[tool.black]
extend-exclude = "analysis_software/intanutil/"
line-length = 99